PCA Notebook
meyer-lab/Fc-deconvolute pull request #18
Opened 2021-05-10 00:03 UTC by sumedha-k

@aarmey could you take a look at the PCA. The first two plots for from our last meeting, and the both bottom two are PCA for adcc and binding. We'll include the complement activation data once we get access to it.

2021-05-10 11:53 UTC, aarmey commented
@sumedha-k this is exactly the right idea. You can move this into a figure file, and note that there are additional receptors with binding data.

2021-05-21 05:30 UTC, sumedha-k commented
@aarmey I moved the PCA and R2X plots into figure6.py and ADCC cross validation stuff into figure7.py

2021-05-21 17:48 UTC, aarmey requested changes
Great. Just two requests.

2021-05-21 17:48 UTC, aarmey commented on deconv/figures/figure6.py
> +    bindingA = pd.read_csv("./deconv/data/Fig2A-FcgRI.csv")
This all should be imported within a reusable function.

2021-05-21 17:48 UTC, aarmey commented on deconv/figures/oldinferfigure.py
> +def makeFigure():
If this is old you can get rid of it.

2021-05-22 05:23 UTC, sumedha-k commented on deconv/figures/figure6.py
> +    bindingA = pd.read_csv("./deconv/data/Fig2A-FcgRI.csv")
So should all of the data imports and pca computation be done in a separate function? Could you specify exactly which lines should be moved into a separate method? Should I put that method into imports.py?

2021-05-22 05:24 UTC, sumedha-k commented on deconv/figures/oldinferfigure.py
> +def makeFigure():
ok, I will delete this file.

2021-05-22 13:03 UTC, aarmey commented on deconv/figures/figure6.py
> +    bindingA = pd.read_csv("./deconv/data/Fig2A-FcgRI.csv")
I'm just thinking all the `read_csv` lines. Other figures will need to do this, too.

2021-10-14 16:54 UTC, merged