Bootstrapping for receptor binding
meyer-lab/Fc-deconvolute pull request #19
Opened 2021-05-19 19:15 UTC by ajtsao1

2021-05-19 21:36 UTC, aarmey requested changes

2021-05-19 21:36 UTC, aarmey commented on bootstrap-test.ipynb
> +{
Delete.

2021-05-19 21:36 UTC, aarmey commented on deconv/data/Fig2A.csv
> +mixture,binding
What are these files?

2021-05-19 21:36 UTC, aarmey commented
I don't see any code changes here...

2021-05-19 21:53 UTC, ajtsao1 commented
Oops, I had done everything in a notebook and forgot to add the code into figure 5. Just pushed changes to the figure file.

2021-05-19 22:03 UTC, aarmey commented
Ok, please resolve my other comments first.

2021-05-19 22:08 UTC, ajtsao1 commented on deconv/data/Fig2A.csv
> +mixture,binding
I reorganized the data so that it is one column of observations, indexed by mixture type. I think this is the form the resample function wants the data in, rather than the matrix form it was in before.

2021-05-20 03:30 UTC, aarmey commented
Ok, in this case, the files should include the mixtures' names, not a number. Also, please delete the other data files.

2021-05-21 23:51 UTC, ajtsao1 commented
Okay, I can add in the mixture names but I think we might still need the column of numbers. I tried it with just the mixture names and the indexing seemed to be off. The resampling worked but then the data was reordered and plotted alphabetically instead of in the original order.

2021-05-22 03:22 UTC, aarmey commented
Keeping the numbers is fine.

2021-05-22 04:31 UTC, merged

2021-05-22 04:37 UTC, ajtsao1 commented
Oh no, I didn't mean to merge. Trying to undo it now..