receptor binding bootstrapping continued
meyer-lab/Fc-deconvolute pull request #21
Opened 2021-05-22 07:05 UTC by ajtsao1

Hi @aarmey I accidentally merged my previous pull request but Sumedha helped me revert everything back. Sorry about that! 

I put all the previous + new changes in this PR: updated the binding data files to include mixture names, updated the load_bindingData function for the new files, and added grouping to the bootstrapping plots. I made a function in imports.py to group all R1s together but I can’t figure out why the figure5 file isn’t recognizing the function. That is what’s causing the build error but the same code worked in a notebook so I attached the results here. I left the R2s ungrouped and R3s are using the ADCC groups.
![grouped](https://user-images.githubusercontent.com/58233382/119217763-38bf0880-ba91-11eb-89f8-fe72f905b0e7.jpg)

2021-05-22 13:05 UTC, aarmey requested changes
One change then this can be merged.

2021-05-22 13:05 UTC, aarmey commented on deconv/imports.py
> +    fig2D = pd.read_csv("./deconv/data/Fig2D.csv", index_col=0)
Last request—please bring back descriptive filenames. Like, this one can be `Fig2D-FcgRIIb.csv`.

2021-05-22 21:07 UTC, ajtsao1 commented
Okay, I changed the file names to what they were before. Is there anything I should do to fix the build error? I'm still not sure why the R1_groups function isn't being recognized.

2021-05-22 21:11 UTC, aarmey commented on deconv/figures/figure5.py
> +    R1_groups = R1_groups()
@ajtsao1, you can't name a variable the same name as a function. Otherwise, how does Python know to what you are referring?

2021-05-22 21:18 UTC, ajtsao1 commented on deconv/figures/figure5.py
> +    R1_groups = R1_groups()
Oh, I see.. thank you. I'll fix that now.

2021-06-02 12:18 UTC, ajtsao1 commented
Hi @aarmey I put the binding cross validation into figure8.py because Sumedha has been working on the fig6-7 files. I think the results look good! 
Also, the last commit fixes the binding error bars but I don’t know if this was the right way to fix it. The problem is that the 67th percentile of the resampled data is sometimes lower than the mean of the inferred (not resampled) deconv value. The difference of those values is the upper error so when it is negative, this error is subtracted instead of added to the deconv value. This causes the error bar to not reach the top of the main bar. I changed those differences into absolute values so that there is always an upper and lower error on the plots, but I’m not sure if this is really fixing the issue. It only happens on the R2s so I wonder if finding groups for those might help.

2021-06-02 14:12 UTC, aarmey approved these changes
This works great for now. Long-term (for the paper) I think we'll need a different approach to the uncertainty quantification. Remind me next time we meet and we can walk through it.

2021-06-02 19:09 UTC, merged