updated imports
meyer-lab/Fc-deconvolute pull request #31
Opened 2021-11-05 22:54 UTC by sumedha-k

updated imports method and figure and emcee files

2021-11-06 03:00 UTC, aarmey requested changes

2021-11-06 03:00 UTC, aarmey commented on deconv/figures/figure4.py
> +    figA = pd.read_csv("./deconv/data/fig3a.csv")
What is this data?

2021-11-06 03:00 UTC, aarmey commented on deconv/imports.py
> +from numpy.lib.function_base import append
Is this used?

2021-11-06 23:10 UTC, sumedha-k commented on deconv/figures/figure4.py
> +    figA = pd.read_csv("./deconv/data/fig3a.csv")
Since this figure is using bootstrapping to calculate error bars, it needs access to all of the ADCC data, not just the means. In modified imports function, we only return the mean ADCC value so the additional csv reading is required here.

2021-11-06 23:11 UTC, sumedha-k commented on deconv/figures/figure4.py
> +    figA = pd.read_csv("./deconv/data/fig3a.csv")
Since we'll be removing this in the future, I didn't see the point of making a separate imports method that returns all of the ADCC data.

2021-11-06 23:12 UTC, sumedha-k commented on deconv/imports.py
> +from numpy.lib.function_base import append
Nope. I'll remove it

2021-11-06 23:13 UTC, sumedha-k commented on deconv/emceeDeconv.py
> +from scipy.sparse import data
I'll remove it

2021-11-07 03:04 UTC, aarmey commented on deconv/figures/figure4.py
> +    figA = pd.read_csv("./deconv/data/fig3a.csv")
Ok, makes sense.

2021-11-07 03:12 UTC, aarmey approved these changes

2021-11-07 03:12 UTC, merged