figure 2
meyer-lab/Fc-deconvolute pull request #33
Opened 2021-11-19 19:12 UTC by sumedha-k

@aarmey here's figure 2
![image](https://user-images.githubusercontent.com/48239303/142678430-1932cfbc-2cc0-4bdb-a322-8c1c3c0d3dfa.png)

2021-11-19 21:02 UTC, aarmey requested changes
Please just replace the Fig. 2 file.

2021-11-24 01:52 UTC, sumedha-k commented
@aarmey do you know what this error is? I'm not getting it when I ran it locally.

2021-11-24 01:54 UTC, sumedha-k commented
This is what the new figure looks like:
![image](https://user-images.githubusercontent.com/48239303/143157245-b2e9f692-d0d3-4f46-a6ca-4271c56fc367.png)

2021-11-24 01:55 UTC, sumedha-k commented
However I'm not sure that this is how we want to commute the error bars. 
`p33 = np.transpose(np.dot(p33_scores, p33_loadings))
 p66 = np.transpose(np.dot(p66_scores, p66_loadings))`

2021-11-24 18:20 UTC, aarmey requested changes
One edit, then this should be ready to merge.

2021-11-24 18:20 UTC, aarmey commented on deconv/figures/figure2.py
> +        ax[i].set_xticklabels(glycans, rotation=90)
Your figure function has to return `f`. Once that's added I expect this will build.

2021-12-01 00:54 UTC, sumedha-k commented
@aarmey Returning f in the previous commit seemed to fix it. But I just pushed another commit to delete figure 11 and the build failed on figure 2 again?

2021-12-01 01:30 UTC, aarmey commented
No, the build failed on Fig. 11. Fig. 2 just was already running and finished.

2021-12-07 22:47 UTC, aarmey commented
I fixed the issue of the quantile amount versus the error bar. Also, the quantiles have to be solved *after* reconstructing all the samples. Will merge this if it builds.

2021-12-07 22:50 UTC, merged