adding notebook for bootstrap
meyer-lab/Fc-deconvolute pull request #5
Opened 2021-02-15 21:05 UTC by sumedha-k

The codes is in testNotebook2.pynb

2021-02-15 21:52 UTC, aarmey requested changes
You're resetting `random_state=0` on every iteration, so all your resamplings are identical.

2021-02-15 22:06 UTC, sumedha-k commented
Oh my goodness- I completely forgot to take that out

2021-02-15 22:09 UTC, sumedha-k commented
@aarmey here's the new graph, I currently have the sample size set to 40, should I change this number at all?

2021-02-15 22:31 UTC, sumedha-k commented
If everything looks good, should I add it to a new python file under figures?

2021-02-16 02:03 UTC, aarmey commented
@sumedha-k I think you can add this to figure1.py!

2021-02-20 19:06 UTC, sumedha-k commented
@aarmey The build error is "no module named 'sklearn'"

2021-02-20 19:07 UTC, aarmey commented
Add `scikit-learn==0.24.1` to `requirements.txt`

2021-03-06 20:24 UTC, sumedha-k commented
@aarmey I attempted to commute the error terms using the ols solver that we discussed last week. I know you suggested that I use np.linalg.pinv(X) for (X' X)^{-1}, but I don't think they are functionally equivalent because pinv returns a non-square matrix. Regardless, I think I have a bug because my error terms are all really small, so I was hoping you could take a look. Everything is in testNotebook2.pynb starting from cell 7.

2021-03-07 23:35 UTC, aarmey reviewed
I think the issue is that the newer way only quantifies the data uncertainty, and virtually all of the uncertainty comes from the variance of the model. We can use bootstrapping—I've pointed out some changes to make, then we can get this merged.

2021-03-07 23:35 UTC, aarmey commented on deconv/figures/figure1.py
> +def makeFigureWithError():
Make a `figure2.py` file.

2021-03-07 23:35 UTC, aarmey commented on deconv/figures/figure1.py
> +    mean3a = np.mean(glycans3a, axis=0)
The center of a bootstrap plot should not be the mean of samples, it should be the result without resampling.

2021-03-07 23:35 UTC, aarmey commented on deconv/figures/figure1.py
> +    error3a = np.std(glycans3a, axis=0)
The error bars needn't be symmetric. Take the 33rd and 66th quantiles to get lower and upper bar ranges. If `yerr` gives two values then it plots asymmetric error bars.

2021-03-09 17:49 UTC, aarmey commented
These were quick fixes so I took care of them. Merging!

2021-03-09 17:50 UTC, merged